import os


class Config:
    SECRET_KEY = os.getenv('PYZZLE_SECRET_KEY', 'pyzzle-dev-secret')
    CORS_ORIGINS = os.getenv('PYZZLE_CORS_ORIGINS', '*')
    HEARTBEAT_INTERVAL_SECONDS = int(os.getenv('PYZZLE_HEARTBEAT_INTERVAL_SECONDS', '60'))
    SESSION_IDLE_TIMEOUT_SECONDS = int(os.getenv('PYZZLE_SESSION_IDLE_TIMEOUT_SECONDS', '600'))
    CLEANUP_INTERVAL_SECONDS = int(os.getenv('PYZZLE_CLEANUP_INTERVAL_SECONDS', '15'))
    RUN_TIMEOUT_SECONDS = int(os.getenv('PYZZLE_RUN_TIMEOUT_SECONDS', '120'))
    MAX_SUBMISSIONS_PER_USER = int(os.getenv('PYZZLE_MAX_SUBMISSIONS_PER_USER', '20'))
